export const APP_LOADED = 'APP_LOADED';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const ALPHA_ORDER_FILTER = 'ALPHA_ORDER_FILTER';
export const MOST_RESENT_FILTER = 'MOST_RESENT_FILTER';
export const LOWEST_PRICE_FILTER = 'LOWEST_PRICE_FILTER';

// export const  =  ;
