export const APP_LOADED = 'APP_LOADED';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const ALPHA_ORDER_FILTER = 'ALPHA_ORDER_FILTER';
export const MOST_RESENT_FILTER = 'MOST_RESENT_FILTER';
export const LOWEST_PRICE_FILTER = 'LOWEST_PRICE_FILTER';

export const ADD_PRODUCT_CART = 'PRODUCT_TO_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const CHANGE_PRODUCT_AMOUNT = 'CHANGE_PRODUCT_AMOUNT';

export const CHANGE_CUSTOMER_TYPE = 'CHANGE_CUSTOMER_TYPE';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const DELETE_CUSTOMER_DATA = 'DELETE_CUSTOMER_DATA';

export const SAVE_CUSTOMER = 'SAVE_CUSTOMER';
export const SAVE_CUSTOMER_SUCCESS = 'SAVE_CUSTOMER_SUCCESS';
export const SAVE_CUSTOMER_FAIL = 'SAVE_CUSTOMER_FAIL';

export const PLACE_ORDER = 'PLACE_ORDER';
export const START_AGAIN = 'START_AGAIN';
