export const APP_LOADED = 'APP_LOADED';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const ALPHA_ORDER_FILTER = 'ALPHA_ORDER_FILTER';
export const MOST_RESENT_FILTER = 'MOST_RESENT_FILTER';
export const LOWEST_PRICE_FILTER = 'LOWEST_PRICE_FILTER';

export const ADD_PRODUCT_CART = 'PRODUCT_TO_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const CHANGE_PRODUCT_AMOUNT = 'CHANGE_PRODUCT_AMOUNT';
// export const  =  ;
